### ISSUE TITLE
How to integrate with Symfony 4?

### ISSUE THREAD

**Issue by mateusfmello** [jacklul/monolog-telegram#1]
Can anyone tell me a tutorial on how to integrate Monolog Telegram Handler with Symfony 4?

**Comment by jacklul** [comment]
As per Symfony documentation you have to register the handler and formatter as services then use 'service' handler in monolog configuration.

Example dev configuration:

services.yml
```php
(...)

    telegram_handler:
        class: jacklul\MonologTelegramHandler\TelegramHandler
        arguments:
            - 'BOT TOKEN'
            - 'CHAT ID'
        calls:
        - method: setFormatter
          arguments:
          - '@telegram_formatter'

    telegram_formatter:
        class: jacklul\MonologTelegramHandler\TelegramFormatter
```

monolog.yml
```php
(...)

        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            handler: telegram
            level: debug
            channels: ["!event"]
			
        telegram:
            type: service
            id: telegram_handler
```

**Comment by MaruanBO** [comment]
Hi sr jack, first thanks!, i have some problems:

Telegram API error: Not Found

**Comment by jacklul** [comment]
> Hi sr jack, first thanks!, i have some problems:
> 
> Telegram API error: Not Found

Check your bot token
