### ISSUE TITLE
Insert emoji option

### ISSUE THREAD

**Issue by paulo-hortelan** [jacklul/monolog-telegram#3]
Would be cool and more intuitive to have an emoji by `level_name` type (⚠️ for warning, etc.). The format would be like this:

`%emoji% %level_name%</b> (%channel%) [%date%]\n\n%message%\n\n%context%%extra%`

If you think this is a good idea, can I be assigned to do it?

**Comment by jacklul** [comment]
I'm open for PRs, but I personally dislike putting the emoji everywhere these days.
So it should be implemented as optional thing.

**Comment by paulo-hortelan** [comment]
I don't like it too but it really makes a difference when analyzing a large amount of warnings and errors in a massive optical network. I'll do it as an optional thing, don't worry
